import pytest
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4
from decimal import Decimal

from schemas.property import PropertyCreate, PropertyUpdate
from services.property import PropertyService
from models.models import Property, Locality


@pytest.mark.asyncio
async def test_create_property():
    """
    Tests creating a property listing. Validates that Postgres repository is called,
    Gemini AI service is triggered, and MongoDB search index is updated.
    """
    db_session = MagicMock()
    mongo_db = MagicMock()

    locality_id = uuid4()
    prop_create = PropertyCreate(
        title="3 BHK Villa in RS Puram",
        property_type="Villa",
        listing_type="Sale",
        price=Decimal("15000000.00"),
        area_sqft=Decimal("2400.00"),
        bedrooms=3,
        bathrooms=4,
        latitude=11.0112,
        longitude=76.9458,
        locality_id=locality_id,
        city="Coimbatore",
        state="Tamil Nadu",
        source="Scraper",
        listing_url="http://example.com/listings/1"
    )

    with patch("services.property.AIService") as mock_ai_class, \
         patch("services.property.PropertyRepository") as mock_postgres_repo_class, \
         patch("services.property.MongoSearchRepository") as mock_mongo_repo_class:
         
        # Create standard return record
        db_prop = Property(
            id=uuid4(),
            title="3 BHK Villa in RS Puram",
            property_type="Villa",
            listing_type="Sale",
            price=Decimal("15000000.00"),
            area_sqft=Decimal("2400.00"),
            bedrooms=3,
            bathrooms=4,
            latitude=11.0112,
            longitude=76.9458,
            locality_id=locality_id,
            city="Coimbatore",
            state="Tamil Nadu",
            source="Scraper",
            listing_url="http://example.com/listings/1",
            ai_description="Premium RS Puram villa details generated by AI.",
            ai_investment_rating="Grade: A | Analysis: Great location deal."
        )
        
        # Setup mocks behavior
        mock_postgres_repo = mock_postgres_repo_class.return_value
        mock_postgres_repo.create = AsyncMock(return_value=db_prop)
        
        mock_mongo_repo = mock_mongo_repo_class.return_value
        mock_mongo_repo.index_property = AsyncMock()

        mock_ai = mock_ai_class.return_value
        mock_ai.generate_property_description = AsyncMock(return_value="Premium RS Puram villa details generated by AI.")
        mock_ai.evaluate_property_deal = AsyncMock(return_value="Grade: A | Analysis: Great location deal.")

        # Execute
        service = PropertyService(db_session, mongo_db)
        res = await service.create_property(prop_create)
        
        # Assertions
        assert res.id is not None
        assert res.title == "3 BHK Villa in RS Puram"
        assert res.ai_description == "Premium RS Puram villa details generated by AI."
        assert res.ai_investment_rating == "Grade: A | Analysis: Great location deal."
        
        # Verify correct dependencies were invoked
        mock_postgres_repo.create.assert_called_once()
        mock_mongo_repo.index_property.assert_called_once()
        mock_ai.generate_property_description.assert_called_once()


@pytest.mark.asyncio
async def test_get_property():
    """
    Tests reading a single property listing detail.
    """
    db_session = MagicMock()
    mongo_db = MagicMock()
    prop_id = uuid4()

    with patch("services.property.PropertyRepository") as mock_postgres_repo_class:
        db_prop = Property(
            id=prop_id,
            title="Commercial Land in Peelamedu"
        )
        mock_postgres_repo = mock_postgres_repo_class.return_value
        mock_postgres_repo.get_by_id = AsyncMock(return_value=db_prop)

        service = PropertyService(db_session, mongo_db)
        res = await service.get_property(prop_id)

        assert res.id == prop_id
        assert res.title == "Commercial Land in Peelamedu"
        mock_postgres_repo.get_by_id.assert_called_once_with(prop_id)


@pytest.mark.asyncio
async def test_list_properties_with_text_search():
    """
    Tests listing properties with full-text search parameters.
    Checks that MongoDB is queried for matching IDs, which are then fetched from Postgres.
    """
    db_session = MagicMock()
    mongo_db = MagicMock()
    
    match_id = uuid4()

    with patch("services.property.PropertyRepository") as mock_postgres_repo_class, \
         patch("services.property.MongoSearchRepository") as mock_mongo_repo_class:
         
        mock_mongo_repo = mock_mongo_repo_class.return_value
        mock_mongo_repo.search_properties_ids = AsyncMock(return_value=[match_id])

        db_prop = Property(
            id=match_id,
            title="PSG tech nearby apartment"
        )
        
        # Setup mock db response
        mock_db_result = MagicMock()
        mock_db_result.scalars.return_value.all.return_value = [db_prop]
        
        mock_postgres_repo = mock_postgres_repo_class.return_value
        mock_postgres_repo.db.execute = AsyncMock(return_value=mock_db_result)

        # Execute
        service = PropertyService(db_session, mongo_db)
        results, count = await service.list_properties(search="PSG tech", limit=10)

        # Assertions
        assert count == 1
        assert results[0].id == match_id
        assert results[0].title == "PSG tech nearby apartment"
        mock_mongo_repo.search_properties_ids.assert_called_once_with("PSG tech", limit=10, skip=0)


@pytest.mark.asyncio
async def test_update_property():
    """
    Tests updating an existing property listing and syncing the search index.
    """
    db_session = MagicMock()
    mongo_db = MagicMock()
    prop_id = uuid4()

    prop_update = PropertyUpdate(price=Decimal("16000000.00"))

    with patch("services.property.PropertyRepository") as mock_postgres_repo_class, \
         patch("services.property.MongoSearchRepository") as mock_mongo_repo_class:
         
        db_prop = Property(
            id=prop_id,
            title="3 BHK Villa in RS Puram",
            property_type="Villa",
            listing_type="Sale",
            price=Decimal("16000000.00"),
            area_sqft=Decimal("2400.00"),
            ai_description="Updated description text."
        )
        
        mock_postgres_repo = mock_postgres_repo_class.return_value
        mock_postgres_repo.update = AsyncMock(return_value=db_prop)
        
        mock_mongo_repo = mock_mongo_repo_class.return_value
        mock_mongo_repo.index_property = AsyncMock()

        # Execute
        service = PropertyService(db_session, mongo_db)
        res = await service.update_property(prop_id, prop_update)

        # Assertions
        assert res.price == Decimal("16000000.00")
        mock_postgres_repo.update.assert_called_once_with(prop_id, prop_update)
        mock_mongo_repo.index_property.assert_called_once()


@pytest.mark.asyncio
async def test_delete_property():
    """
    Tests deleting an existing listing from Postgres and MongoDB.
    """
    db_session = MagicMock()
    mongo_db = MagicMock()
    prop_id = uuid4()

    with patch("services.property.PropertyRepository") as mock_postgres_repo_class, \
         patch("services.property.MongoSearchRepository") as mock_mongo_repo_class:
         
        mock_postgres_repo = mock_postgres_repo_class.return_value
        mock_postgres_repo.delete = AsyncMock(return_value=True)
        
        mock_mongo_repo = mock_mongo_repo_class.return_value
        mock_mongo_repo.delete_property = AsyncMock()

        # Execute
        service = PropertyService(db_session, mongo_db)
        deleted = await service.delete_property(prop_id)

        # Assertions
        assert deleted is True
        mock_postgres_repo.delete.assert_called_once_with(prop_id)
        mock_mongo_repo.delete_property.assert_called_once_with(prop_id)
